In [13]:
#1-> Numpy Array 运算
import numpy as np

In [14]:
height = [1.73 ,1.68, 1.71, 1.89, 1.79]

In [15]:
#numpy.array->对数组整体进行运算
np_height = np.array(height)

In [16]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [17]:
np_weight = np.array(weight)

In [18]:
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [19]:
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [20]:
#np_height与np_weight进行运算
bmi = np_weight / (np_height ** 2)

In [21]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [22]:
#两个array相加, 结果为对应元素相加
np_weight + np_height

array([67.13, 60.88, 65.31, 90.29, 70.49])

In [34]:
#2-> numpy的基本统计学

In [35]:
import numpy
data = []
for i in range(10):
    data.append(i)
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
#求平均值
np.mean(data)

4.5

In [38]:
#求中值
np.median(data)

4.5

In [39]:
#求和
np.sum(data)

45

In [40]:
#排序
np.sort(data)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#相关系数
np.corrcoef(data[::1],data[::-1])

array([[ 1., -1.],
       [-1.,  1.]])

In [43]:
#标准差
np.std(data)

2.8722813232690143

In [44]:
#数据的产生 -- 随机抽样
#np.random.normal(均值，标准差。数量)

In [45]:
ran_height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [46]:
ran_height

array([2.18, 1.74, 1.29, ..., 1.82, 1.51, 2.  ])

In [47]:
ran_weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [48]:
ran_weight

array([65.51, 68.84, 43.51, ..., 45.18, 42.3 , 66.36])

In [50]:
#np_city = np.column_stack(ran_height, ran_weight)